### ISSUE TITLE
A note about the *ALL section

### ISSUE THREAD

**Issue by SnkXIII** [MuxaJlbl4/Vita-Nearest-Neighbour#1]
Hi there. Plugin works really well so cheers!

My config file didn't have an *ALL category by default and I'm unsure if it is supposed to so excuse this if it does.
I started installing this by adding the *ALL category at the end of the config file, which never worked.

I moved the category up above individual title ID section which got it working.

Do you think a note about this *ALL category would be of any use?

**Comment by MuxaJlbl4** [comment]
That strange, i have *ALL section at bottom too, but all works fine. However i [add more info](https://github.com/MuxaJlbl4/Vita-Nearest-Neighbour/commit/ae6eb2b656e71f49b49d4f0942534b5038a20bae). Thanks!
